# See README for instructions on possible configurations

[model]
model_name = "WDX12_rna002_v0_4_2"

[flowcell]
flowcell_type = "flongle"


[[balancers]]
balance_threshold = 0.05
min_stat = 100
balance_type = "adapter_count"
name = "adapter_count1"
channel_frac = 0.4
reject_duration = 0.1

blacklist_barcode08 = true
watch_barcode00 = false

[[balancers]]
balance_threshold = 0.05
min_stat = 30
balance_type = "adapter_count"
name = "adapter_count2"
channel_frac = 0.4
reject_duration = 0.2

blacklist_barcode03 = true
watch_for_missing = false
max_barcode01 = 40

[[balancers]]
balance_threshold = 0.05
min_stat = 100
balance_type = "none"
channel_frac = 0.1
reject_duration = 0.3

blacklist_barcode03 = true
watch_for_missing = false

[processing]
nproc_segmentation = 2
nproc_classification = 4

[acquisition]
max_missed_start_offset = 400
max_chunk_size = 12000

[balancing]
pred_conf_threshold = 0.27

[reporting]
save_every_sec = 5
save_path = "results"
