# See README for instructions on possible configurations

[model]
model_name = "WDX12_rna002_v0_4_4"

[flowcell]
flowcell_type = "flongle"

[[balancers]]
balance_threshold = 0.05
min_stat = 100
balance_type = "reject_all"

watch_barcode06 = false

[processing]
nproc_segmentation = 2
nproc_classification = 4

[acquisition]
max_missed_start_offset = 400
max_chunk_size = 12000

[balancing]
pred_conf_threshold = 0.2

[reporting]
save_every_sec = 5
save_path = "results"
