[core]
min_obs_adapter = 2500

[streaming]
min_obs_post_loc = 300
search_increment_step = 100

pA_mean_window = 20
pA_mean_range = [90.0, 130.0]

pA_var_window = 100
pA_var_range = [-inf, 20.0]

median_shift_window = 2000
median_shift_range = [20.0, inf]

polyA_window = 300
polyA_med_range = [90.0, 130.0]
polyA_local_range = [0.0, 10.0]

[real_range]
detect_open_pores = false
real_signal_check = true
mean_window = 300
mean_start_range = [50.0, 100.0]
mean_end_range = [75.0, 120.0]
max_obs_local_range = 5000
local_range = [10.0, 35.0]
adapter_mad_range = [3.0, 12.0]
